### ISSUE TITLE
batchsize = 1 传入模型的问题

### ISSUE THREAD

**Issue by britney-code** [ylhz/tf_to_pytorch_model#10]
作者，你好 ，batchsize = 1的时候，传入模型获得logits的有的模型维度为[1,1001] 有的模型维度为[1001] 如何修改呢？

**Comment by ylhz** [comment]
你好，可以在torch_net中对应的模型```def forward()```中调整为统一的输出格式。也可以在输出后调整处理logits的代码。

**Comment by zchoi** [comment]
solid
